artifacts_root: artifacts

#---data ingestion config---
data_ingestion:
  root_dir: artifacts/data_ingestion
  s3_bucket: aircraft-engine-data
  s3_keys:
    train: bronze/train_FD001.txt
    test: bronze/test_FD001.txt
    rul: bronze/RUL_FD001.txt
  local_data_dir: artifacts/data_ingestion/data

#---data validation config---
data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data
  status_file: artifacts/data_validation/status.json

#---data transformation config---
data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/data
  processed_dir: artifacts/data_transformation/processed
  s3_silver_prefix: silver/
  train_output: train_processed.parquet
  test_output: test_processed.parquet
  scaler_path: artifacts/data_transformation/scaler.pkl

#---data feature engineering config---
data_feature_engineering:
  root_dir: artifacts/data_feature_engineering
  processed_dir: artifacts/data_transformation/processed
  output_dir: artifacts/data_feature_engineering/
  s3_gold_prefix: gold/
  X_train: X_train.npy
  y_train: y_train.npy
  X_val: X_val.npy
  y_val: y_val.npy
  X_test: X_test.npy
  y_test: y_test.npy

#---model trainer config---
model_trainer:
  root_dir: artifacts/model_trainer
  gold_dir: artifacts/data_feature_engineering
  model_path: artifacts/model_trainer/model.keras
  history_path: artifacts/model_trainer/history.json
  s3_artifact_prefix: artifacts/

#---model evaluation config---
model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_trainer/model.keras
  gold_dir: artifacts/data_feature_engineering
  metrics_path: artifacts/model_evaluation/metrics.json
  results_path: artifacts/model_evaluation/results.parquet
  confusion_matrix_path: artifacts/model_evaluation/confusion_matrix.png
  prediction_plot_path: artifacts/model_evaluation/pred_vs_true.png
  error_distribution_path: artifacts/model_evaluation/error_distribution.png
  s3_artifact_prefix: artifacts/

#---model registration config---
model_registry:
  root_dir: artifacts/model_registry
  model_path: artifacts/model_trainer/model.keras
  metrics_path: artifacts/model_evaluation/metrics.json

